import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";

import type { StackProfile } from "../projects/stack.js";
import { words } from "../projects/stack.js";
import { globToRegExp, isGenericLayerName, walkProjectFiles } from "./gaps.js";

export const TOKEN_FILE_MARKER = "AUTO-GENERATED by aos-mcp from .artemis/design/tokens.json";
export const TOKEN_NAMES_FILE = "token-names.json";

const MAX_SCAN_FILES = 500;
const MAX_SCAN_BYTES = 256 * 1024;
const MAX_SAMPLES = 3;

const CODE_GLOBS = [
  "**/*.dart",
  "**/*.kt",
  "**/*.java",
  "**/*.swift",
  "**/*.ts",
  "**/*.tsx",
  "**/*.css",
  "**/*.scss",
  "**/*.xml"
];

export interface DesignColorInput {
  hex: string;
  usageCount: number;
  sampleLayers: string[];
}

export interface ColorToken {
  /** Canonical dotted name, e.g. `color.brand.primary`. */
  name: string;
  /** Normalized `#RRGGBBAA` value; alias tokens carry `{target}`. */
  value: string;
  modes: Record<string, string>;
  aliasOf?: string;
  usageCount: number;
  samples: string[];
  needsReview: boolean;
}

export type TokenActionKind = "new" | "unchanged" | "updated" | "unused";

export interface TokenAction {
  name: string;
  action: TokenActionKind;
  value: string;
  needsReview: boolean;
}

export interface MergeColorTokensResult {
  tokens: ColorToken[];
  actions: TokenAction[];
}

export interface HardcodedColorHit {
  file: string;
  line: number;
  value: string;
}

export interface StackTokenFileWrite {
  relativePath: string;
  content: string;
  format: "android-xml" | "dart" | "ts" | "css" | "swift" | "xcassets-json";
}

export interface StackTokenWrite extends StackTokenFileWrite {
  extraFiles?: StackTokenFileWrite[];
}

const CATEGORY_RULES: Array<{ re: RegExp; category: string }> = [
  { re: /(text|label|title|heading|subtitle|caption|body|font|copy)/, category: "text" },
  { re: /(background|surface|bg|card|container|scrim|overlay|sheet|panel)/, category: "surface" },
  { re: /(border|stroke|divider|outline|separator)/, category: "border" },
  {
    re: /(brand|primary|accent|cta|button|action|link|danger|error|warning|success|info)/,
    category: "brand"
  }
];

/** Expand any #RGB/#RGBA/#RRGGBB/#RRGGBBAA to canonical uppercase `#RRGGBBAA`. */
export function normalizeHexColor(input: string): string | null {
  const raw = input.trim().replace(/^#/, "");
  if (!/^[0-9a-fA-F]+$/.test(raw)) return null;
  let body: string;
  if (raw.length === 3) body = `${[...raw].map((char) => char + char).join("")}FF`;
  else if (raw.length === 4) body = [...raw].map((char) => char + char).join("");
  else if (raw.length === 6) body = `${raw}FF`;
  else if (raw.length === 8) body = raw;
  else return null;
  return `#${body.toUpperCase()}`;
}

export { isGenericLayerName };

export function meaningfulLayerSlug(name: string): string | null {
  if (isGenericLayerName(name)) return null;
  const parts = words(name);
  if (parts.length === 0) return null;
  return parts.slice(0, 4).join("_");
}

function categoryFor(slug: string): string {
  const spaced = ` ${slug.replace(/_/g, " ")} `;
  for (const rule of CATEGORY_RULES) {
    if (rule.re.test(spaced)) return rule.category;
  }
  return "base";
}

function hexKey(value: string): string {
  return value.slice(1, 7).toLowerCase();
}

function fingerprint(value: string): string {
  return createHash("sha1").update(value).digest("hex").slice(0, 6);
}

interface CandidateNames {
  names: string[];
  needsReview: boolean;
}

function candidateNamesFor(value: string, samples: string[]): CandidateNames {
  const slugs = [...new Set(samples.map(meaningfulLayerSlug).filter((slug): slug is string => slug !== null))].slice(
    0,
    MAX_SAMPLES
  );
  if (slugs.length >= 2) {
    return {
      names: [`color.base.${hexKey(value)}`, ...slugs.map((slug) => `color.${categoryFor(slug)}.${slug}`)],
      needsReview: true
    };
  }
  if (slugs.length === 1) {
    return { names: [`color.${categoryFor(slugs[0]!)}.${slugs[0]!}`], needsReview: false };
  }
  return { names: [`color.base.${hexKey(value)}`], needsReview: true };
}

function uniqueName(name: string, taken: Set<string>): string {
  if (!taken.has(name)) return name;
  let index = 2;
  while (taken.has(`${name}-${index}`)) index += 1;
  return `${name}-${index}`;
}

function groupDesignColors(colors: DesignColorInput[]): Map<string, { usageCount: number; samples: string[] }> {
  const groups = new Map<string, { usageCount: number; samples: string[] }>();
  for (const color of colors) {
    const value = normalizeHexColor(color.hex);
    if (!value) continue;
    const entry = groups.get(value) ?? { usageCount: 0, samples: [] };
    entry.usageCount += color.usageCount;
    for (const sample of color.sampleLayers) {
      if (!entry.samples.includes(sample) && entry.samples.length < 8) entry.samples.push(sample);
    }
    groups.set(value, entry);
  }
  return groups;
}

function resolvedValueOf(name: string, byName: Map<string, ColorToken>): string | null {
  const seen = new Set<string>();
  let current = byName.get(name);
  while (current?.aliasOf && !seen.has(current.name)) {
    seen.add(current.name);
    current = byName.get(current.aliasOf);
  }
  return current ? current.value : null;
}

/** Merge design colors into the canonical token set with value-frozen naming:
 * - same value → reuse the previously assigned base name (renames never lose history);
 * - new value → derive a semantic name (or use token-names.json override);
 * - values that disappeared from the design → kept, reported as `unused`. */
export function mergeColorTokens(
  designColors: DesignColorInput[],
  existing: ColorToken[],
  overrides: Record<string, string> = {}
): MergeColorTokensResult {
  const byName = new Map(existing.map((token) => [token.name, token]));
  const existingResolved = new Map<string, ColorToken>();
  for (const token of existing) {
    if (token.aliasOf) continue;
    const resolved = resolvedValueOf(token.name, byName);
    if (resolved && !existingResolved.has(resolved)) existingResolved.set(resolved, token);
  }

  const taken = new Set(existing.map((token) => token.name));
  const out = new Map<string, ColorToken>();
  const actions: TokenAction[] = [];
  const groups = [...groupDesignColors(designColors).entries()].sort(
    (a, b) => b[1].usageCount - a[1].usageCount || a[0].localeCompare(b[0])
  );

  for (const [value, info] of groups) {
    const override = overrides[value];
    const derived = candidateNamesFor(value, info.samples);
    const hit = existingResolved.get(value);
    let baseName = override ?? hit?.name ?? derived.names[0]!;
    const baseTaken = taken.has(baseName);
    if (baseTaken && baseName !== hit?.name) baseName = uniqueName(baseName, taken);
    taken.add(baseName);
    out.set(baseName, {
      name: baseName,
      value,
      modes: { default: value },
      usageCount: info.usageCount,
      samples: info.samples,
      needsReview: override ? false : derived.needsReview
    });

    const aliasNames = new Set<string>(override ? [] : derived.names.slice(1));
    for (const token of existing) {
      if (token.aliasOf === hit?.name && token.name !== baseName) aliasNames.add(token.name);
    }
    for (const aliasNameRaw of [...aliasNames].sort()) {
      const prior = byName.get(aliasNameRaw);
      const priorResolved = prior ? resolvedValueOf(prior.name, byName) : null;
      const reusable = prior !== undefined && (prior.aliasOf === baseName || priorResolved === value);
      const aliasName = reusable
        ? aliasNameRaw
        : taken.has(aliasNameRaw)
          ? uniqueName(aliasNameRaw, taken)
          : aliasNameRaw;
      taken.add(aliasName);
      out.set(aliasName, {
        name: aliasName,
        value: `{${baseName}}`,
        modes: { default: `{${baseName}}` },
        aliasOf: baseName,
        usageCount: info.usageCount,
        samples: info.samples,
        needsReview: false
      });
    }

    actions.push({
      name: baseName,
      action: hit ? "unchanged" : "new",
      value,
      needsReview: override ? false : derived.needsReview
    });
  }

  for (const token of existing) {
    if (out.has(token.name)) continue;
    if (token.aliasOf && !out.has(token.aliasOf) && !byName.has(token.aliasOf)) continue;
    out.set(token.name, token);
    actions.push({ name: token.name, action: "unused", value: token.value, needsReview: token.needsReview });
  }

  const tokens = [...out.values()].sort((a, b) => a.name.localeCompare(b.name));
  actions.sort((a, b) => a.name.localeCompare(b.name));
  return { tokens, actions };
}

// ---------------------------------------------------------------------------
// Canonical (DTCG-ish) serialization
// ---------------------------------------------------------------------------

interface DtcgNode {
  [key: string]: unknown;
}

function setNested(root: DtcgNode, parts: string[], leaf: Record<string, unknown>): void {
  let node = root;
  for (const part of parts.slice(0, -1)) {
    const next = node[part];
    if (next && typeof next === "object") node = next as DtcgNode;
    else {
      const created: DtcgNode = {};
      node[part] = created;
      node = created;
    }
  }
  node[parts[parts.length - 1]!] = leaf;
}

export function serializeTokens(tokens: ColorToken[]): string {
  const root: DtcgNode = { $extensions: { aos: { version: 1 } } };
  for (const token of tokens) {
    setNested(root, token.name.split("."), {
      $type: "color",
      $value: token.value,
      $extensions: {
        aos: {
          modes: token.modes,
          usageCount: token.usageCount,
          samples: token.samples,
          needsReview: token.needsReview,
          ...(token.aliasOf ? { aliasOf: token.aliasOf } : {})
        }
      }
    });
  }
  return `${JSON.stringify(root, null, 2)}\n`;
}

export function parseCanonicalTokens(text: string): ColorToken[] {
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    return [];
  }
  if (!parsed || typeof parsed !== "object") return [];
  const tokens: ColorToken[] = [];
  const walk = (node: unknown, parts: string[]): void => {
    if (!node || typeof node !== "object") return;
    const record = node as Record<string, unknown>;
    if (record.$type === "color" && typeof record.$value === "string") {
      const extensions = (record.$extensions ?? {}) as Record<string, unknown>;
      const aos = (extensions.aos ?? {}) as Record<string, unknown>;
      const modes =
        aos.modes && typeof aos.modes === "object"
          ? (aos.modes as Record<string, string>)
          : { default: record.$value };
      tokens.push({
        name: parts.join("."),
        value: record.$value,
        modes,
        ...(typeof aos.aliasOf === "string" ? { aliasOf: aos.aliasOf } : {}),
        usageCount: typeof aos.usageCount === "number" ? aos.usageCount : 0,
        samples: Array.isArray(aos.samples) ? aos.samples.filter((s): s is string => typeof s === "string") : [],
        needsReview: aos.needsReview === true
      });
      return;
    }
    for (const [key, value] of Object.entries(record)) {
      if (key.startsWith("$")) continue;
      walk(value, [...parts, key]);
    }
  };
  walk(parsed, []);
  return tokens.sort((a, b) => a.name.localeCompare(b.name));
}

// ---------------------------------------------------------------------------
// Per-stack generated files
// ---------------------------------------------------------------------------

function toAarrggbb(hex8: string): string {
  return `#${hex8.slice(7, 9)}${hex8.slice(1, 7)}`;
}

function cssColor(hex8: string): string {
  return hex8.endsWith("FF") ? hex8.slice(0, 7) : hex8;
}

function camelMember(name: string): string {
  const parts = name.split(/[^A-Za-z0-9]+/).filter(Boolean);
  if (parts.length === 0) return "token";
  return parts
    .map((part, index) => (index === 0 ? part : `${part[0]!.toUpperCase()}${part.slice(1)}`))
    .join("")
    .replace(/[^A-Za-z0-9_$]/g, "");
}

function colorsetJson(hex8: string): Record<string, unknown> {
  const body = hex8.replace(/^#/, "");
  const channel = (pair: string): string => (Number.parseInt(pair, 16) / 255).toFixed(3);
  return {
    colors: [
      {
        color: {
          "color-space": "srgb",
          components: {
            red: channel(body.slice(0, 2)),
            green: channel(body.slice(2, 4)),
            blue: channel(body.slice(4, 6)),
            alpha: channel(body.slice(6, 8))
          }
        },
        idiom: "universal"
      }
    ],
    info: { author: TOKEN_FILE_MARKER, version: 1 }
  };
}

export function resolveTokenValue(token: ColorToken, tokens: ColorToken[]): string {
  if (!token.aliasOf) return token.value;
  const base = tokens.find((candidate) => candidate.name === token.aliasOf);
  return base?.value ?? token.value;
}

export function renderStackTokenFile(profile: StackProfile, tokens: ColorToken[]): StackTokenWrite | null {
  const target = profile.i18n.tokenFile;
  if (!target) return null;
  const sorted = [...tokens].sort((a, b) => a.name.localeCompare(b.name));

  if (profile.id === "android-native") {
    const lines = [
      '<?xml version="1.0" encoding="utf-8"?>',
      `<!-- ${TOKEN_FILE_MARKER} — do not edit. -->`,
      "<resources>"
    ];
    for (const token of sorted) {
      const value = resolveTokenValue(token, tokens);
      const resource = token.name.replace(/\./g, "_").replace(/[^a-z0-9_]/g, "_");
      lines.push(`  <!-- ${token.name} -->`);
      lines.push(`  <color name="${resource}">${toAarrggbb(value)}</color>`);
    }
    lines.push("</resources>", "");
    return { relativePath: target, content: lines.join("\n"), format: "android-xml" };
  }

  if (profile.id === "flutter") {
    const lines = [
      `// ${TOKEN_FILE_MARKER} — do not edit.`,
      "import 'package:flutter/material.dart';",
      "",
      "abstract final class AosTokens {"
    ];
    for (const token of sorted) {
      const value = resolveTokenValue(token, tokens);
      lines.push(`  /// ${token.name}`);
      lines.push(`  static const Color ${camelMember(token.name)} = Color(0x${toAarrggbb(value).slice(1)});`);
    }
    lines.push("}", "");
    return { relativePath: target, content: lines.join("\n"), format: "dart" };
  }

  if (profile.id === "web") {
    const lines = [`/* ${TOKEN_FILE_MARKER} — do not edit. */`, ":root {"];
    for (const token of sorted) {
      const value = resolveTokenValue(token, tokens);
      lines.push(`  --${token.name.replace(/[._]/g, "-")}: ${cssColor(value)};`);
    }
    lines.push("}", "");
    return { relativePath: target, content: lines.join("\n"), format: "css" };
  }

  if (profile.id === "ios-native") {
    const lines = [`// ${TOKEN_FILE_MARKER} — do not edit.`, "import SwiftUI", "", "enum AosTokens {"];
    const extraFiles: StackTokenFileWrite[] = [];
    for (const token of sorted) {
      const value = resolveTokenValue(token, tokens);
      lines.push(`  /// ${token.name}`);
      lines.push(`  static let ${camelMember(token.name)} = Color("${token.name}")`);
      extraFiles.push({
        relativePath: path.posix.join(
          "Resources",
          "Colors.xcassets",
          `${token.name}.colorset`,
          "Contents.json"
        ),
        content: `${JSON.stringify(colorsetJson(value), null, 2)}\n`,
        format: "xcassets-json"
      });
    }
    lines.push("}", "");
    return { relativePath: target, content: lines.join("\n"), format: "swift", extraFiles };
  }

  const lines = [`/* ${TOKEN_FILE_MARKER} — do not edit. */`, "export const aosTokens = {"];
  for (const token of sorted) {
    const value = resolveTokenValue(token, tokens);
    lines.push(`  ${JSON.stringify(token.name)}: ${JSON.stringify(cssColor(value))},`);
  }
  lines.push("} as const;", "");
  return { relativePath: target, content: lines.join("\n"), format: "ts" };
}

export function contentHasTokenMarker(content: string): boolean {
  return content.includes(TOKEN_FILE_MARKER);
}

export interface StackTokenWriteResult {
  relativePath: string;
  action: "written" | "unchanged" | "planned" | "skipped_unmanaged";
  files?: Array<{ relativePath: string; action: StackTokenWriteResult["action"] }>;
}

/** Idempotent stack-file writer shared by the Figma and pen token importers:
 * same content → `unchanged`; unmanaged file (no generated marker) is left alone
 * unless `overwrite`; `dryRun` reports the planned action without touching disk. */
export function writeStackTokenFile(
  rootDir: string,
  write: StackTokenWrite,
  options: { overwrite?: boolean; dryRun?: boolean } = {}
): StackTokenWriteResult {
  const main = writeStackTokenFileSingle(rootDir, write, options);
  const extras = (write.extraFiles ?? []).map((file) =>
    writeStackTokenFileSingle(rootDir, file, options)
  );
  if (extras.length === 0) return main;
  return {
    ...main,
    files: [main, ...extras].map(({ relativePath, action }) => ({ relativePath, action }))
  };
}

export function skippedTokenFiles(result: StackTokenWriteResult | null): string[] {
  if (!result) return [];
  return [
    ...(result.action === "skipped_unmanaged" ? [result.relativePath] : []),
    ...(result.files ?? [])
      .filter((file) => file.action === "skipped_unmanaged")
      .map((file) => file.relativePath)
  ];
}

function writeStackTokenFileSingle(
  rootDir: string,
  write: StackTokenFileWrite,
  options: { overwrite?: boolean; dryRun?: boolean }
): StackTokenWriteResult {
  const absolute = path.join(rootDir, write.relativePath);
  if (!fs.existsSync(absolute)) {
    if (options.dryRun !== true) {
      fs.mkdirSync(path.dirname(absolute), { recursive: true });
      fs.writeFileSync(absolute, write.content, "utf-8");
      return { relativePath: write.relativePath, action: "written" };
    }
    return { relativePath: write.relativePath, action: "planned" };
  }
  const current = fs.readFileSync(absolute, "utf-8");
  if (current === write.content) return { relativePath: write.relativePath, action: "unchanged" };
  if (!contentHasTokenMarker(current) && options.overwrite !== true) {
    return { relativePath: write.relativePath, action: "skipped_unmanaged" };
  }
  if (options.dryRun !== true) {
    fs.writeFileSync(absolute, write.content, "utf-8");
    return { relativePath: write.relativePath, action: "written" };
  }
  return { relativePath: write.relativePath, action: "planned" };
}

// ---------------------------------------------------------------------------
// Overrides + hardcoded scan
// ---------------------------------------------------------------------------

export function loadTokenOverrides(configDir: string): Record<string, string> {
  const filePath = path.join(configDir, "design", TOKEN_NAMES_FILE);
  try {
    const parsed = JSON.parse(fs.readFileSync(filePath, "utf-8")) as { overrides?: unknown };
    const overrides = parsed.overrides;
    if (!overrides || typeof overrides !== "object") return {};
    const normalized: Record<string, string> = {};
    for (const [key, value] of Object.entries(overrides as Record<string, unknown>)) {
      const color = normalizeHexColor(key);
      if (!color || typeof value !== "string") continue;
      const name = value.trim();
      if (!/^color(\.[a-z0-9_-]+)+$/i.test(name)) continue;
      normalized[color] = name;
    }
    return normalized;
  } catch {
    return {};
  }
}

export function scanHardcodedColors(
  rootDir: string,
  options: { excludeGlobs?: string[]; maxHits?: number } = {}
): HardcodedColorHit[] {
  const exclude = (options.excludeGlobs ?? []).map(globToRegExp);
  const files = walkProjectFiles(rootDir, CODE_GLOBS).slice(0, MAX_SCAN_FILES);
  const hits: HardcodedColorHit[] = [];
  const maxHits = options.maxHits ?? 50;
  for (const file of files) {
    if (exclude.some((regex) => regex.test(file))) continue;
    let text: string;
    try {
      const stat = fs.statSync(path.join(rootDir, file));
      if (!stat.isFile() || stat.size > MAX_SCAN_BYTES) continue;
      text = fs.readFileSync(path.join(rootDir, file), "utf-8");
    } catch {
      continue;
    }
    if (text.includes("\u0000") || contentHasTokenMarker(text) || text.includes(TOKEN_FILE_MARKER)) {
      continue;
    }
    const lines = text.split(/\r?\n/);
    for (let index = 0; index < lines.length && hits.length < maxHits; index += 1) {
      const line = lines[index]!;
      for (const match of line.matchAll(/#([0-9a-fA-F]{3,8})\b/g)) {
        const normalized = normalizeHexColor(match[1]!);
        if (!normalized) continue;
        hits.push({ file, line: index + 1, value: normalized });
      }
      for (const match of line.matchAll(/\b0x([0-9a-fA-F]{8})\b/g)) {
        const raw = match[1]!.toUpperCase();
        hits.push({ file, line: index + 1, value: `#${raw.slice(2)}${raw.slice(0, 2)}` });
      }
    }
    if (hits.length >= maxHits) break;
  }
  return hits;
}

export function tokenFingerprint(tokens: ColorToken[]): string {
  return fingerprint(tokens.map((token) => `${token.name}=${token.value}`).join("|"));
}
