import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";

import type { FigmaNode } from "../vendor/design-context-bridge/figma-rest/resolve.js";
import type { CaseStyle, StackProfile } from "../projects/stack.js";
import { words } from "../projects/stack.js";
import { walkProjectFiles } from "./gaps.js";
import { isGenericLayerName, meaningfulLayerSlug } from "./color.js";
import { errorMessage } from "../util.js";

export const STRINGS_FILE_VERSION = 1;
export const STRING_FILE_MARKER = "AUTO-GENERATED by aos-mcp from .artemis/design/strings.json";
export const RESOLUTIONS_FILE = "resolutions.json";

const MAX_TEXTS = 500;
const MAX_SCAN_FILES = 300;
const MAX_SCAN_BYTES = 256 * 1024;
const ANDROID_NAME_MAX = 100;

export type StringLifecycle =
  | "active"
  | "source_changed"
  | "conflict"
  | "needs_context"
  | "needs_rename"
  | "unused"
  | "resolved";

export interface FigmaTextRecord {
  nodeId: string;
  characters: string;
  canonicalText: string;
  screen: string;
  layer: string;
  element: string;
  placeholders: string[];
  needsContext: boolean;
  needsRename: boolean;
}

export interface StringEntry {
  key: string;
  nodeId: string;
  screen: string;
  layer: string;
  sourceText: string;
  canonicalText: string;
  sourceFingerprint: string;
  placeholders: string[];
  lifecycle: StringLifecycle;
  /** Manual plural confirmation (string-context.json); never persisted here. */
  plural?: PluralSpec;
}

export interface PluralSpec {
  variable: string;
  forms: Record<string, string>;
}

export const STRING_CONTEXT_FILE = "string-context.json";
export const PLURAL_QUANTITIES = ["zero", "one", "two", "few", "many", "other"] as const;
const PLURAL_QUANTITY_SET = new Set<string>(PLURAL_QUANTITIES);
const PLACEHOLDER_NAME_RE = /\{([A-Za-z0-9_]+)\}/g;

export interface LoadedStringContext {
  file: string;
  contexts: Map<string, PluralSpec>;
  errors: string[];
}

export function loadStringContext(configDirAbs: string): LoadedStringContext {
  const file = path.join(configDirAbs, "design", STRING_CONTEXT_FILE);
  const result: LoadedStringContext = { file, contexts: new Map(), errors: [] };
  let raw: string;
  try {
    raw = fs.readFileSync(file, "utf-8");
  } catch {
    return result;
  }
  let parsed: { entries?: Record<string, unknown> };
  try {
    parsed = JSON.parse(raw) as { entries?: Record<string, unknown> };
  } catch (error) {
    result.errors.push(`${STRING_CONTEXT_FILE} 解析失败: ${errorMessage(error)}`);
    return result;
  }
  const entries = parsed.entries;
  if (!entries || typeof entries !== "object" || Array.isArray(entries)) {
    result.errors.push(`${STRING_CONTEXT_FILE} 缺少 entries 对象`);
    return result;
  }
  for (const [key, value] of Object.entries(entries)) {
    const error = validatePluralContext(value);
    if (error) {
      result.errors.push(`「${key}」: ${error}`);
      continue;
    }
    const record = value as { plural: { variable?: unknown; forms: Record<string, string> } };
    result.contexts.set(key, {
      variable: typeof record.plural.variable === "string" ? record.plural.variable : "count",
      forms: { ...record.plural.forms }
    });
  }
  return result;
}

function validatePluralContext(value: unknown): string | null {
  if (!value || typeof value !== "object" || Array.isArray(value)) return "条目必须是对象";
  const plural = (value as { plural?: unknown }).plural;
  if (!plural || typeof plural !== "object" || Array.isArray(plural)) return "缺少 plural 对象";
  const variableRaw = (plural as { variable?: unknown }).variable;
  if (variableRaw !== undefined && (typeof variableRaw !== "string" || !/^[A-Za-z0-9_]+$/.test(variableRaw))) {
    return "variable 必须是标识符";
  }
  const variable = typeof variableRaw === "string" ? variableRaw : "count";
  const forms = (plural as { forms?: unknown }).forms;
  if (!forms || typeof forms !== "object" || Array.isArray(forms)) return "缺少 forms 对象";
  const entries = Object.entries(forms as Record<string, unknown>);
  if (entries.length === 0) return "forms 不能为空";
  if (!Object.prototype.hasOwnProperty.call(forms, "other")) return "forms 必须包含 other";
  for (const [quantity, form] of entries) {
    if (!PLURAL_QUANTITY_SET.has(quantity)) return `不支持的 quantity "${quantity}"`;
    if (typeof form !== "string" || form.trim() === "") return `forms.${quantity} 必须是非空字符串`;
    for (const match of form.matchAll(PLACEHOLDER_NAME_RE)) {
      if (match[1] !== variable) return `forms.${quantity} 仅支持 {${variable}}，发现 {${match[1]}}`;
    }
  }
  return null;
}

export interface StringsFile {
  version: number;
  sourceLocale: string;
  entries: StringEntry[];
}

export interface MigrationSuggestion {
  fromKey: string;
  toKey: string;
  nodeId: string;
  reason: string;
  status: "suggested";
}

export interface ReuseSuggestion {
  key: string;
  reuseOf: string;
  text: string;
}

export interface MergeStringsResult {
  entries: StringEntry[];
  migrations: MigrationSuggestion[];
  reuseSuggestions: ReuseSuggestion[];
  unused: string[];
  sourceChanged: string[];
}

export interface HardcodedStringHit {
  file: string;
  line: number;
  text: string;
  stack: "android-native" | "flutter";
}

export interface ResourceConflict {
  key: string;
  existing: string;
  incoming: string;
}

export interface ResourceWrite {
  relativePath: string;
  action: "written" | "unchanged";
  conflicts: ResourceConflict[];
  content: string;
}

// ---------------------------------------------------------------------------
// Text collection
// ---------------------------------------------------------------------------

export function canonicalizePlaceholders(text: string): { canonicalText: string; placeholders: string[] } {
  let counter = 0;
  let out = text.replace(/%(\d+)\$[sdif@]/g, (_match, index: string) => `{arg${index}}`);
  out = out.replace(/%[sdif@]/g, () => `{arg${++counter}}`);
  const placeholders = [...new Set([...out.matchAll(/\{([A-Za-z0-9_]+)\}/g)].map((match) => match[1]!))];
  return { canonicalText: out, placeholders };
}

export function normalizedText(text: string): string {
  return text.normalize("NFC").trim();
}

function shortHash(value: string): string {
  return createHash("sha1").update(value).digest("hex").slice(0, 6);
}

interface CollectContext {
  screen: string;
  ancestors: string[];
}

function elementHintFor(layer: string, context: CollectContext): string {
  if (!isGenericLayerName(layer)) return layer;
  for (let index = context.ancestors.length - 1; index >= 0; index -= 1) {
    const candidate = context.ancestors[index]!;
    if (candidate !== context.screen && !isGenericLayerName(candidate)) return candidate;
  }
  return layer;
}

function collectFromNode(node: FigmaNode, context: CollectContext, out: FigmaTextRecord[]): void {
  const isComponent = node.type === "COMPONENT" || node.type === "COMPONENT_SET";
  const next: CollectContext = isComponent
    ? { screen: node.name || context.screen, ancestors: [] }
    : { screen: context.screen, ancestors: [...context.ancestors, node.name] };

  if (node.type === "TEXT") {
    const raw = typeof node.characters === "string" ? node.characters : "";
    const characters = normalizedText(raw);
    if (characters !== "") {
      const { canonicalText, placeholders } = canonicalizePlaceholders(characters);
      const overrides = node.characterStyleOverrides;
      const mixedStyle = Array.isArray(overrides) && overrides.some((value) => Number(value) !== 0);
      const dynamic = /\$\{|\{\{/.test(characters);
      const layer = node.name || "text";
      out.push({
        nodeId: node.id,
        characters,
        canonicalText,
        screen: context.screen || "app",
        layer,
        element: elementHintFor(layer, context),
        placeholders,
        needsContext: mixedStyle || dynamic,
        needsRename: isGenericLayerName(layer)
      });
    }
    return;
  }

  for (const child of node.children ?? []) {
    collectFromNode(child, next, out);
    if (out.length >= MAX_TEXTS) return;
  }
}

export function collectFigmaTexts(document: FigmaNode): FigmaTextRecord[] {
  const records: FigmaTextRecord[] = [];
  for (const page of document.children ?? []) {
    for (const screen of page.children ?? []) {
      collectFromNode(screen, { screen: screen.name || page.name || "app", ancestors: [] }, records);
      if (records.length >= MAX_TEXTS) return records;
    }
  }
  return records;
}

// ---------------------------------------------------------------------------
// Key derivation
// ---------------------------------------------------------------------------

function slugPart(value: string): string {
  return words(value).slice(0, 4).join("_") || "x";
}

export function deriveCanonicalKey(record: FigmaTextRecord): string {
  const screen = slugPart(record.screen);
  const element = record.needsRename
    ? `text_${shortHash(record.nodeId)}`
    : meaningfulLayerSlug(record.element) ?? `text_${shortHash(record.nodeId)}`;
  return `${screen}.${element}`;
}

function uniquifyKey(base: string, taken: Set<string>): string {
  let key = base;
  let index = 2;
  while (taken.has(key)) {
    key = `${base}_${index}`;
    index += 1;
  }
  return key;
}

export function platformKey(canonicalKey: string, style: CaseStyle): string {
  const parts = canonicalKey.split(".").map((part) => part.split("_")).flat();
  switch (style) {
    case "snake":
      return androidResourceName(parts.join("_"));
    case "kebab":
      return parts.join("-");
    case "pascal":
      return parts.map((part) => `${part[0]!.toUpperCase()}${part.slice(1)}`).join("");
    case "camel":
      return parts
        .map((part, index) => (index === 0 ? part : `${part[0]!.toUpperCase()}${part.slice(1)}`))
        .join("");
  }
}

export function androidResourceName(name: string): string {
  const sanitized = name.toLowerCase().replace(/[^a-z0-9_]/g, "_").replace(/^(\d)/, "_$1");
  if (sanitized.length <= ANDROID_NAME_MAX) return sanitized;
  return `${sanitized.slice(0, ANDROID_NAME_MAX - 7)}_${shortHash(sanitized)}`;
}

export function sourceFingerprintOf(canonicalText: string, placeholders: string[]): string {
  return `sha256:${createHash("sha256").update(`${canonicalText}|${placeholders.join(",")}`).digest("hex")}`;
}

// ---------------------------------------------------------------------------
// Merge with the frozen mapping
// ---------------------------------------------------------------------------

export function mergeStrings(existing: StringEntry[], records: FigmaTextRecord[]): MergeStringsResult {
  const byNode = new Map(existing.map((entry) => [entry.nodeId, entry]));
  const byKey = new Map(existing.map((entry) => [entry.key, entry]));
  const taken = new Set(existing.map((entry) => entry.key));
  const docNodeIds = new Set(records.map((record) => record.nodeId));

  const entries: StringEntry[] = [];
  const migrations: MigrationSuggestion[] = [];
  const reuseSuggestions: ReuseSuggestion[] = [];
  const rebound = new Set<string>();
  const sorted = [...records].sort((a, b) => a.nodeId.localeCompare(b.nodeId));

  for (const record of sorted) {
    const fingerprint = sourceFingerprintOf(record.canonicalText, record.placeholders);
    const direct = byNode.get(record.nodeId);
    if (direct) {
      const changed = direct.canonicalText !== record.canonicalText;
      entries.push({
        ...direct,
        screen: record.screen,
        layer: record.layer,
        sourceText: record.characters,
        canonicalText: record.canonicalText,
        sourceFingerprint: fingerprint,
        placeholders: record.placeholders,
        lifecycle: record.needsContext ? "needs_context" : changed ? "source_changed" : "active"
      });
      continue;
    }

    const base = deriveCanonicalKey(record);
    const collision = byKey.get(base);
    if (collision && !docNodeIds.has(collision.nodeId)) {
      taken.add(base);
      rebound.add(collision.key);
      migrations.push({
        fromKey: collision.key,
        toKey: base,
        nodeId: record.nodeId,
        reason: "node 身份变化但派生 key 相同：key 已沿用，翻译保持有效",
        status: "suggested"
      });
      entries.push({
        ...collision,
        nodeId: record.nodeId,
        screen: record.screen,
        layer: record.layer,
        sourceText: record.characters,
        canonicalText: record.canonicalText,
        sourceFingerprint: fingerprint,
        placeholders: record.placeholders,
        lifecycle: record.needsContext
          ? "needs_context"
          : collision.canonicalText !== record.canonicalText
            ? "source_changed"
            : "active"
      });
      continue;
    }

    let key = base;
    let duplicated = false;
    if (collision && docNodeIds.has(collision.nodeId)) {
      duplicated = true;
      key = uniquifyKey(base, taken);
      migrations.push({
        fromKey: base,
        toKey: key,
        nodeId: record.nodeId,
        reason: "同一屏幕内派生 key 命中存活节点：已加后缀，需人工重命名",
        status: "suggested"
      });
    } else if (taken.has(base)) {
      duplicated = true;
      key = uniquifyKey(base, taken);
      migrations.push({
        fromKey: base,
        toKey: key,
        nodeId: record.nodeId,
        reason: "同一批次内派生 key 冲突（重复文案节点）：已加后缀，需人工确认",
        status: "suggested"
      });
    }
    taken.add(key);

    const match = entries.find((entry) => entry.canonicalText === record.canonicalText);
    if (match) {
      reuseSuggestions.push({ key, reuseOf: match.key, text: record.canonicalText });
    }

    entries.push({
      key,
      nodeId: record.nodeId,
      screen: record.screen,
      layer: record.layer,
      sourceText: record.characters,
      canonicalText: record.canonicalText,
      sourceFingerprint: fingerprint,
      placeholders: record.placeholders,
      lifecycle: record.needsContext
        ? "needs_context"
        : record.needsRename || duplicated
          ? "needs_rename"
          : "active"
    });
  }

  const unused: string[] = [];
  for (const entry of existing) {
    if (rebound.has(entry.key) || docNodeIds.has(entry.nodeId)) continue;
    if (entries.some((candidate) => candidate.key === entry.key)) continue;
    entries.push({ ...entry, lifecycle: "unused" });
    unused.push(entry.key);
  }

  entries.sort((a, b) => a.key.localeCompare(b.key));
  const sourceChanged = entries.filter((entry) => entry.lifecycle === "source_changed").map((entry) => entry.key);
  return { entries, migrations, reuseSuggestions, unused, sourceChanged };
}

// ---------------------------------------------------------------------------
// Persistence
// ---------------------------------------------------------------------------

export function serializeStrings(entries: StringEntry[], sourceLocale: string): string {
  const sorted = [...entries].sort((a, b) => a.key.localeCompare(b.key));
  const lines = [`{`, `  "version": ${STRINGS_FILE_VERSION},`, `  "sourceLocale": ${JSON.stringify(sourceLocale)},`, `  "entries": [`];
  sorted.forEach((entry, index) => {
    const record = {
      key: entry.key,
      nodeId: entry.nodeId,
      screen: entry.screen,
      layer: entry.layer,
      sourceText: entry.sourceText,
      canonicalText: entry.canonicalText,
      sourceFingerprint: entry.sourceFingerprint,
      placeholders: entry.placeholders,
      lifecycle: entry.lifecycle
    };
    lines.push(`    ${JSON.stringify(record)}${index === sorted.length - 1 ? "" : ","}`);
  });
  lines.push("  ]", "}", "");
  return lines.join("\n");
}

export function parseStrings(text: string): StringsFile {
  try {
    const parsed = JSON.parse(text) as Partial<StringsFile>;
    if (!Array.isArray(parsed.entries)) throw new Error("entries 缺失");
    return {
      version: typeof parsed.version === "number" ? parsed.version : STRINGS_FILE_VERSION,
      sourceLocale: typeof parsed.sourceLocale === "string" ? parsed.sourceLocale : "zh",
      entries: parsed.entries as StringEntry[]
    };
  } catch {
    return { version: STRINGS_FILE_VERSION, sourceLocale: "zh", entries: [] };
  }
}

export function loadResolvedConflicts(configDir: string): Set<string> {
  try {
    const raw = fs.readFileSync(path.join(configDir, "design", RESOLUTIONS_FILE), "utf-8");
    const parsed = JSON.parse(raw) as { conflicts?: Record<string, unknown> };
    return new Set(Object.keys(parsed.conflicts ?? {}));
  } catch {
    return new Set();
  }
}

// ---------------------------------------------------------------------------
// Resource writers
// ---------------------------------------------------------------------------

function escapeXml(value: string): string {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function unescapeXml(value: string): string {
  return value
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, "&")
    .replace(/\\'/g, "'")
    .replace(/\\"/g, '"')
    .replace(/\\n/g, "\n")
    .replace(/\\t/g, "\t")
    .replace(/\\\\/g, "\\");
}

export function canonicalTextToAndroid(text: string): string {
  const positions = new Map<string, number>();
  let out = text.replace(/\{([A-Za-z0-9_]+)\}/g, (_match, name: string) => {
    if (!positions.has(name)) positions.set(name, positions.size + 1);
    return `%${positions.get(name)}$s`;
  });
  out = out.replace(/%(?!\d+\$s)/g, "%%");
  out = out.replace(/'/g, "\\'");
  if (out.startsWith("@") || out.startsWith("?")) out = `\\${out}`;
  return escapeXml(out);
}

export function canonicalTextToIcu(text: string): string {
  return text;
}

/** ICU plural message from a confirmed context: `{count, plural, one {…} other {…}}`. */
export function renderIcuPlural(plural: PluralSpec): string {
  const parts = PLURAL_QUANTITIES.filter((quantity) => plural.forms[quantity] !== undefined).map(
    (quantity) => `${quantity} {${plural.forms[quantity]!}}`
  );
  return `{${plural.variable}, plural, ${parts.join(" ")}}`;
}

function isWritable(entry: StringEntry): boolean {
  if (entry.lifecycle === "conflict") return false;
  if (entry.lifecycle === "needs_context") return entry.plural !== undefined;
  return true;
}

function pluralFormToAndroid(form: string, variable: string): string {
  let out = form.replace(/%/g, "%%").split(`{${variable}}`).join("%1$d");
  out = out.replace(/'/g, "\\'");
  if (out.startsWith("@") || out.startsWith("?")) out = `\\${out}`;
  return escapeXml(out);
}

function pluralFormToIos(form: string, variable: string): string {
  return escapeXml(form.replace(/%/g, "%%").split(`{${variable}}`).join("%d"));
}

/** ICU → iOS format value (placeholders, `%` escaping). Quote/backslash escapes
 * are applied by the writer (`escapeIos`) so merge comparisons stay logical. */
export function canonicalTextToIos(text: string): string {
  const names = new Set([...text.matchAll(/\{([A-Za-z0-9_]+)\}/g)].map((match) => match[1]!));
  const positions = new Map<string, number>();
  let out = text.replace(/\{([A-Za-z0-9_]+)\}/g, (_match, name: string) => {
    if (!positions.has(name)) positions.set(name, positions.size + 1);
    return names.size > 1 ? `%${positions.get(name)}$@` : "%@";
  });
  out = out.replace(/%(?!\d+\$@|@)/g, "%%");
  return out;
}

function escapeIos(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r");
}

function unescapeIos(value: string): string {
  return value
    .replace(/\\n/g, "\n")
    .replace(/\\r/g, "\r")
    .replace(/\\"/g, '"')
    .replace(/\\\\/g, "\\");
}

interface ExistingAndroidResource {
  value: string;
  file: string;
}

export function parseAndroidStringsFiles(
  rootDir: string,
  excludeFile: string | null
): Map<string, ExistingAndroidResource> {
  const result = new Map<string, ExistingAndroidResource>();
  const files = walkProjectFiles(rootDir, ["app/src/main/res/values*/**/*.xml"]);
  for (const file of files) {
    if (excludeFile && file === excludeFile) continue;
    let text: string;
    try {
      text = fs.readFileSync(path.join(rootDir, file), "utf-8");
    } catch {
      continue;
    }
    for (const match of text.matchAll(/<string\s+name="([^"]+)"[^>]*>([\s\S]*?)<\/string>/g)) {
      const key = match[1]!;
      if (!result.has(key)) result.set(key, { value: unescapeXml(match[2]!.trim()), file });
    }
  }
  return result;
}

export function renderAndroidStrings(
  profile: StackProfile,
  entries: StringEntry[],
  rootDir: string,
  localeDir: string
): ResourceWrite {
  const relativePath = profile.i18n.stringsFile.replace("{localeDir}", localeDir);
  const existingText = readExisting(path.join(rootDir, relativePath));
  const existingOwn = parseAndroidGeneratedContent(existingText);
  const other = parseAndroidStringsFiles(rootDir, relativePath);
  const conflicts: ResourceConflict[] = [];
  const merged = new Map<string, string>();
  const plurals = new Map<string, PluralSpec>();

  for (const [key, value] of existingOwn) merged.set(key, value);

  for (const entry of entries) {
    if (!isWritable(entry)) continue;
    const key = platformKey(entry.key, profile.i18n.keyStyle);
    if (entry.plural) {
      const foreign = other.get(key);
      if (foreign) {
        conflicts.push({ key, existing: foreign.value, incoming: renderIcuPlural(entry.plural) });
      }
      merged.delete(key);
      if (!foreign) plurals.set(key, entry.plural);
      continue;
    }
    const value = canonicalTextToAndroid(entry.canonicalText);
    const foreign = other.get(key);
    if (foreign) {
      if (unescapeXml(value) !== foreign.value) {
        conflicts.push({ key, existing: foreign.value, incoming: unescapeXml(value) });
      }
      merged.delete(key);
      continue;
    }
    merged.set(key, value);
  }

  const lines = [
    '<?xml version="1.0" encoding="utf-8"?>',
    `<!-- ${STRING_FILE_MARKER} — do not edit. -->`,
    "<resources>"
  ];
  for (const key of [...merged.keys()].sort()) {
    lines.push(`  <string name="${key}">${merged.get(key)}</string>`);
  }
  for (const key of [...plurals.keys()].sort()) {
    const plural = plurals.get(key)!;
    lines.push(`  <plurals name="${key}">`);
    for (const quantity of PLURAL_QUANTITIES) {
      const form = plural.forms[quantity];
      if (form === undefined) continue;
      lines.push(`    <item quantity="${quantity}">${pluralFormToAndroid(form, plural.variable)}</item>`);
    }
    lines.push("  </plurals>");
  }
  lines.push("</resources>", "");
  const content = lines.join("\n");
  const action: ResourceWrite["action"] = existingText === content ? "unchanged" : "written";
  return { relativePath, action, conflicts, content };
}

function parseAndroidGeneratedContent(text: string | null): Map<string, string> {
  const map = new Map<string, string>();
  if (!text) return map;
  for (const match of text.matchAll(/<string\s+name="([^"]+)"[^>]*>([\s\S]*?)<\/string>/g)) {
    map.set(match[1]!, match[2]!.trim());
  }
  return map;
}

export function renderJsonLocale(
  profile: StackProfile,
  entries: StringEntry[],
  rootDir: string,
  locale: string,
  options: { metadata?: boolean } = {}
): ResourceWrite {
  const relativePath = profile.i18n.stringsFile.replace("{locale}", locale);
  const existingText = readExisting(path.join(rootDir, relativePath));
  let existing: Record<string, unknown> = {};
  try {
    const parsed = existingText ? (JSON.parse(existingText) as unknown) : {};
    if (parsed && typeof parsed === "object") existing = parsed as Record<string, unknown>;
  } catch {
    existing = {};
  }
  const conflicts: ResourceConflict[] = [];
  const merged: Record<string, unknown> = { ...existing };

  for (const entry of entries) {
    if (!isWritable(entry)) continue;
    const key = platformKey(entry.key, profile.i18n.keyStyle);
    const value = entry.plural ? renderIcuPlural(entry.plural) : canonicalTextToIcu(entry.canonicalText);
    if (Object.prototype.hasOwnProperty.call(existing, key)) {
      if (existing[key] !== value) {
        conflicts.push({ key, existing: String(existing[key]), incoming: value });
      }
      continue;
    }
    merged[key] = value;
    if (options.metadata === true && entry.placeholders.length > 0) {
      const metadata: Record<string, unknown> = {};
      for (const placeholder of entry.placeholders) {
        metadata[placeholder] = {
          type: entry.plural && placeholder === entry.plural.variable ? "int" : "String"
        };
      }
      merged[`@${key}`] = { placeholders: metadata };
    }
  }

  const ordered: Record<string, unknown> = {};
  if (typeof merged["@@locale"] === "string") ordered["@@locale"] = merged["@@locale"];
  for (const key of Object.keys(merged)) {
    if (key === "@@locale") continue;
    if (!key.startsWith("@")) ordered[key] = merged[key];
  }
  for (const key of Object.keys(merged)) {
    if (!key.startsWith("@")) continue;
    ordered[key] = merged[key];
  }
  const content = `${JSON.stringify(ordered, null, 2)}\n`;
  const action: ResourceWrite["action"] = existingText === content ? "unchanged" : "written";
  return { relativePath, action, conflicts, content };
}

export function renderFlutterArb(
  profile: StackProfile,
  entries: StringEntry[],
  rootDir: string,
  locale: string
): ResourceWrite {
  return renderJsonLocale(profile, entries, rootDir, locale, { metadata: true });
}

export function renderIosStrings(
  profile: StackProfile,
  entries: StringEntry[],
  rootDir: string,
  locale: string
): ResourceWrite {
  const relativePath = profile.i18n.stringsFile.replace("{locale}", locale);
  const existingText = readExisting(path.join(rootDir, relativePath));
  const existing = parseIosStrings(existingText);
  const conflicts: ResourceConflict[] = [];
  const merged = new Map<string, string>(existing);

  for (const entry of entries) {
    if (entry.lifecycle === "conflict") continue;
    const key = platformKey(entry.key, profile.i18n.keyStyle);
    if (entry.plural) {
      merged.delete(key);
      continue;
    }
    if (entry.lifecycle === "needs_context") continue;
    const value = canonicalTextToIos(entry.canonicalText);
    const prior = existing.get(key);
    if (prior !== undefined) {
      if (prior !== value) {
        conflicts.push({ key, existing: prior, incoming: value });
      }
      continue;
    }
    merged.set(key, value);
  }

  const lines = [`/* ${STRING_FILE_MARKER} — do not edit. */`];
  for (const [key, value] of [...merged.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
    lines.push(`"${key}" = "${escapeIos(value)}";`);
  }
  lines.push("");
  const content = lines.join("\n");
  const action: ResourceWrite["action"] = existingText === content ? "unchanged" : "written";
  return { relativePath, action, conflicts, content };
}

export function parseIosStrings(text: string | null): Map<string, string> {
  const map = new Map<string, string>();
  if (!text) return map;
  for (const match of text.matchAll(/"((?:[^"\\]|\\.)*)"\s*=\s*"((?:[^"\\]|\\.)*)"\s*;/g)) {
    map.set(unescapeIos(match[1]!), unescapeIos(match[2]!));
  }
  return map;
}

/** `.stringsdict` for confirmed plurals (`.strings` cannot express them). Returns
 * null when there is nothing to render, so plural-free projects stay clean. */
export function renderIosStringsdict(
  profile: StackProfile,
  entries: StringEntry[],
  rootDir: string,
  locale: string
): ResourceWrite | null {
  const pluralEntries = entries
    .filter((entry) => isWritable(entry) && entry.plural !== undefined)
    .sort((a, b) => a.key.localeCompare(b.key));
  if (pluralEntries.length === 0) return null;

  const relativePath = profile.i18n.stringsFile
    .replace("{locale}", locale)
    .replace(/\.strings$/, ".stringsdict");
  const existingText = readExisting(path.join(rootDir, relativePath));
  const lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    `<!-- ${STRING_FILE_MARKER} — do not edit. -->`,
    '<plist version="1.0">',
    "<dict>"
  ];
  for (const entry of pluralEntries) {
    const plural = entry.plural!;
    const key = platformKey(entry.key, profile.i18n.keyStyle);
    lines.push(`  <key>${escapeXml(key)}</key>`, "  <dict>");
    lines.push("    <key>NSStringLocalizedFormatKey</key>", `    <string>%#@${plural.variable}@</string>`);
    lines.push(`    <key>${plural.variable}</key>`, "    <dict>");
    lines.push("      <key>NSStringFormatSpecTypeKey</key>", "      <string>NSStringPluralRuleType</string>");
    lines.push("      <key>NSStringFormatValueTypeKey</key>", "      <string>d</string>");
    for (const quantity of PLURAL_QUANTITIES) {
      const form = plural.forms[quantity];
      if (form === undefined) continue;
      lines.push(`      <key>${quantity}</key>`);
      lines.push(`      <string>${pluralFormToIos(form, plural.variable)}</string>`);
    }
    lines.push("    </dict>", "  </dict>");
  }
  lines.push("</dict>", "</plist>", "");

  const content = lines.join("\n");
  const action: ResourceWrite["action"] = existingText === content ? "unchanged" : "written";
  return { relativePath, action, conflicts: [], content };
}

function readExisting(absolute: string): string | null {
  try {
    return fs.readFileSync(absolute, "utf-8");
  } catch {
    return null;
  }
}

export function writeResourceFile(rootDir: string, write: ResourceWrite): ResourceWrite["action"] {
  if (write.action === "unchanged") return "unchanged";
  const absolute = path.join(rootDir, write.relativePath);
  fs.mkdirSync(path.dirname(absolute), { recursive: true });
  fs.writeFileSync(absolute, write.content, "utf-8");
  return "written";
}

// ---------------------------------------------------------------------------
// Hardcoded strings scan
// ---------------------------------------------------------------------------

export function scanHardcodedStrings(
  rootDir: string,
  stackId: "android-native" | "flutter",
  options: { maxHits?: number } = {}
): HardcodedStringHit[] {
  const hits: HardcodedStringHit[] = [];
  const maxHits = options.maxHits ?? 50;
  const scanFile = (file: string, regex: RegExp): void => {
    let text: string;
    try {
      const stat = fs.statSync(path.join(rootDir, file));
      if (!stat.isFile() || stat.size > MAX_SCAN_BYTES) return;
      text = fs.readFileSync(path.join(rootDir, file), "utf-8");
    } catch {
      return;
    }
    if (text.includes(STRING_FILE_MARKER)) return;
    const lines = text.split(/\r?\n/);
    for (let index = 0; index < lines.length && hits.length < maxHits; index += 1) {
      const line = lines[index]!;
      regex.lastIndex = 0;
      for (const match of line.matchAll(regex)) {
        const value = match[2] ?? match[1] ?? "";
        if (value === "" || value.includes("$")) continue;
        hits.push({ file, line: index + 1, text: value, stack: stackId });
      }
    }
  };

  if (stackId === "android-native") {
    const files = walkProjectFiles(rootDir, ["app/src/main/res/layout*/**/*.xml"]).slice(0, MAX_SCAN_FILES);
    const regex = /android:(?:text|hint|contentDescription)\s*=\s*"([^"]*)"/g;
    for (const file of files) {
      if (hits.length >= maxHits) break;
      scanFile(file, regex);
    }
    return hits.filter((hit) => !hit.text.startsWith("@") && !hit.text.startsWith("?"));
  }

  const files = walkProjectFiles(rootDir, ["lib/**/*.dart"]).slice(0, MAX_SCAN_FILES);
  const regex = /\bText\(\s*(?:const\s+)?(['"])([^'"]*)\1/g;
  for (const file of files) {
    if (hits.length >= maxHits) break;
    scanFile(file, regex);
  }
  return hits;
}

export function stringsExcludeGlobs(profile: StackProfile | null): string[] {
  const globs = ["**/*.arb"];
  if (profile?.i18n.stringsFile) {
    globs.push(profile.i18n.stringsFile.replace("{locale}", "*").replace("{localeDir}", "*"));
  }
  return globs;
}
